/** Original sprite artwork, shared by the world and inventory. */
export const palette: Record<string, string> = {
  o: '#252438',
  d: '#433951',
  s: '#685671',
  l: '#a59aa0',
  w: '#fff4d1',
  g: '#3c7660',
  G: '#68ab68',
  v: '#acd879',
  y: '#efc565',
  Y: '#fff3a6',
  b: '#436f94',
  B: '#72b6bc',
  c: '#ade6db',
  r: '#b65458',
  R: '#ed8470',
  p: '#8165a4',
  P: '#b58bca',
  f: '#efba8e',
  F: '#ffdbab',
  h: '#865a48',
  H: '#bc8254',
};
export const sprites: Record<string, string[]> = {
  explorer: [
    '........................',
    '..........oooo..........',
    '........ooGGGGoo........',
    '.......oGGvvvvGGo.......',
    '......oGGvvvvGGGGo......',
    '.....oGGGGGGGGGGGGo.....',
    '.....oGGGGGooooGGGo.....',
    '.....ooooooHHHHoooo.....',
    '......oHHHhffffHo.......',
    '......oHHfFoFofHo.......',
    '......offfFoFoffo.......',
    '.......offFFFFfo........',
    '........ooFFoo..........',
    '......oogGyyGgoo........',
    '.....ofogGyyGofo........',
    '.....oFogGGGGoFo........',
    '.....oFooGGGooFo........',
    '......ooogyyoGoo........',
    '........oyyyyo..........',
    '.......ogGGGGgo.........',
    '.......ogGooGgo.........',
    '.......oHHo.oHHo........',
    '......oHHHo.oHHHo.......',
    '......ooooo.ooooo.......',
  ],
  patroller: [
    '........................',
    '.........oooooo.........',
    '........olwwwwlo........',
    '.......olwwwwwwlo.......',
    '......olwwwllwwwlo......',
    '......olwlololwlwo......',
    '......ollolYlolllo......',
    '.......osooooooso.......',
    '........ossrrsso........',
    '.......oorRRRRroo.......',
    '.....oollorRRrolloo.....',
    '....olwllorRRrolwwlo....',
    '....olwllorRRrollllo....',
    '.....olloHHHHHolloo.....',
    '......oooyyyyooollo.....',
    '........orRRro.olwo.....',
    '.......orRRRRroolwo.....',
    '.......ooooooo.oooo.....',
    '.......ollollo..........',
    '.......ollollo..........',
    '......olllolllo.........',
    '......oooo.oooo.........',
    '........................',
    '........................',
  ],
  turret: [
    '........................',
    '.........oooooo.........',
    '........olwwwwlo........',
    '.......olwwYwwwlo.......',
    '......olwwYYYYwllo......',
    '......olllwwwwlllo......',
    '.....oooooooooooooo.....',
    '.....oHHHHHHHHHHHHo.....',
    '.....oHyyHHHHHyyHHo.....',
    '.....oHyoorRrooHyHo.....',
    '.....oHyoRYYYRoHyHo.....',
    '.....oHyoRYwYRoHyHo.....',
    '.....oHyooRRRooHyHo.....',
    '.....oHHHHoooHHHHHo.....',
    '.....oHHHhHHHhHHHHo.....',
    '......oHHHHHHHHHHo......',
    '......ollllllllllo......',
    '.....olwwwwwwwwwwlo.....',
    '.....ollllllllllllo.....',
    '....olsssssssssssslo....',
    '....oooooooooooooooo....',
    '........................',
    '........................',
    '........................',
  ],
  chaser: [
    '........................',
    '.........oooo...........',
    '........oPPPpo..........',
    '.......oPPPpppo.........',
    '......oPPPPppppo........',
    '.....oPPwPPpppppo.......',
    '....oPPwPPPppppppo......',
    '...oPPPPPPPPppppppo.....',
    '...oPPoooooooooPPpo.....',
    '...oPooYYoooYYooPpo.....',
    '...oPoYwYoooYwYoPpo.....',
    '...oPooYYoooYYooPpo.....',
    '....oPoooooooooPpo......',
    '....oPPPPPPPPppppo......',
    '.....oPPPPPPppppo.......',
    '.....opPPPPppppo........',
    '....opppPPppppppo.......',
    '....opppppppppppo.......',
    '.....ooooppooooo........',
    '........oooo............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  strike: [
    '................',
    '...........ooo..',
    '..........owwo..',
    '.........owwlo..',
    '........owwlo...',
    '.......owwlo....',
    '......owwlo.....',
    '.....owwlo......',
    '..ooowwlo.......',
    '..oyoolo........',
    '...oyyo.........',
    '...ooyyoo.......',
    '..oHoooyyo......',
    '.oHHo..oo.......',
    '.ooo............',
    '................',
  ],
  shield: [
    '................',
    '.......oo.......',
    '....oooyyooo....',
    '..ooyYYwwYYyoo..',
    '..oyYbbbbbbYyo..',
    '..oybBBccBBbyo..',
    '..oybBBccBBbyo..',
    '..oybccccccbyo..',
    '..oybBBccBBbyo..',
    '...oyBBccBByo...',
    '...oyBBBBBByo...',
    '....oyBBBByo....',
    '.....oyBByo.....',
    '......oyyo......',
    '.......oo.......',
    '................',
  ],
  step1: [
    '................',
    '................',
    '....ooooo.......',
    '....oGGGo.......',
    '....oGvGo.......',
    '....oGGGo.......',
    '....oHHHo.......',
    '....oHHHoooo....',
    '....oHHHHHHHo...',
    '....oHHHHHHHo...',
    '....oyyyyyyyo...',
    '....ooooooooo...',
    '................',
    '..BB............',
    '.cc.............',
    '................',
  ],
  arrow: [
    '................',
    '..........yyy...',
    '.........oyyyo..',
    '........ooooyo..',
    '.......owoo.....',
    '......owo.......',
    '.....owo........',
    '....owo.........',
    '...owo..........',
    '..owoo..........',
    '.ocBoo..........',
    '.oBBo...........',
    '.ooo............',
    '................',
    '................',
    '................',
  ],
  boost: [
    '................',
    '...oooooooooo...',
    '...oyyyyyyyyo...',
    '....owwwwwwo....',
    '....obYYYbbo....',
    '.....obYbbo.....',
    '......oyyo......',
    '......oyyo......',
    '.....obYbbo.....',
    '....obYYYbbo....',
    '....obYYYbbo....',
    '....owwwwwwo....',
    '...oyyyyyyyyo...',
    '...oooooooooo...',
    '................',
    '................',
  ],
  redraw: [
    '................',
    '......oooo......',
    '....ooYYYYoo....',
    '...oYYooooYYo...',
    '..oYYo....oYYo..',
    '..oYo......oYo..',
    '.oYoo......ooYo.',
    '.oyyyyo..oyyyyo.',
    '..oooo....oooo..',
    '................',
    '...oBBooooBBBo..',
    '...oBBBccBBBBo..',
    '....oBBBBBBBo...',
    '.....ooooooo....',
    '................',
    '................',
  ],
  heart: [
    '................',
    '..ooo....ooo....',
    '.oRRRo..oRRRo...',
    'oRwwRRo.oRRRRo..',
    'oRwwRRRoRRRRRo..',
    'oRRRRRRRRRRRRo..',
    '.oRRRRRRRRRRo...',
    '..oRRRRRRRRo....',
    '...oRRRRRRo.....',
    '....oRRRRo......',
    '.....oRRo.......',
    '......oo........',
    '................',
    '................',
    '................',
    '................',
  ],
  taunt: [
    '................',
    '....oooooooo....',
    '...oyyyyyyyyo...',
    '..oyYYwwwwYYyo..',
    '..oyYrrrrrrYyo..',
    '..oyrRRwwRRryo..',
    '..oyrRRwwRRryo..',
    '..oyrRRwwRRryo..',
    '..oyrRRRRRRryo..',
    '..oyrRRwwRRryo..',
    '..oyYrrrrrrYyo..',
    '...oyyyyyyyyo...',
    '....oooooooo....',
    '................',
    '................',
    '................',
  ],
  dash: [
    '................',
    '........ooo.....',
    '.......oyYo.....',
    '......oyYYo.....',
    '.....oyYYo......',
    '....oyYYooooo...',
    '...oyYYYYYYyo...',
    '...ooooYYyyo....',
    '......oyYyo.....',
    '.....oyYyo......',
    '....oyYyo.......',
    '...oyyyo........',
    '...oyyo.........',
    '...ooo..........',
    '................',
    '................',
  ],
  swap: [
    '................',
    '....ooo.........',
    '.....oGoo.......',
    '..oooovGooooo...',
    '.oGGGGvGGGGGGo..',
    '..ooooooooooo...',
    '................',
    '................',
    '...ooooooooooo..',
    '..oBBBBBcBBBBBo.',
    '...ooooocBooo...',
    '.......ooBo.....',
    '.........ooo....',
    '................',
    '................',
    '................',
  ],
};
sprites.step2 = Array.from({ length: 24 }, (_, y) =>
  Array.from({ length: 24 }, (_, x) => {
    const front = sprites.step1[y - 6]?.[x] ?? '.';
    const back = sprites.step1[y]?.[x - 7] ?? '.';
    return front !== '.' ? front : back;
  }).join(''),
);
sprites.duo = sprites.explorer;
export function pixelSvg(name: string) {
  const rows = sprites[name] ?? sprites.explorer;
  return `<svg class="pixel-sprite" viewBox="0 0 ${Math.max(...rows.map((r) => r.length))} ${rows.length}" shape-rendering="crispEdges" aria-hidden="true">${rows.flatMap((row, y) => [...row].map((p, x) => (palette[p] ? `<rect x="${x}" y="${y}" width="1" height="1" fill="${palette[p]}"/>` : ''))).join('')}</svg>`;
}
